import type { Def, Scenario } from "./types";

export const PATH_COST = 12;
export const MAP = 36;
export const DAY_SECONDS = 18;
export const DAYS_PER_MONTH = 8;

export const DEFS: Def[] = [
  {
    id: "wonder-round",
    name: "Wonder Round",
    blurb: "Painted horses, a brass organ, and guests who refuse to dismount.",
    category: "ride",
    w: 3,
    h: 3,
    cost: 820,
    kind: "carousel",
    color: "#c24a3a",
    roof: "#f3ead7",
    height: 38,
    startUnlocked: true,
    excitement: 3.2,
    intensity: 1.4,
    nausea: 0.8,
    capacity: 12,
    duration: 8,
    runningCost: 12,
    reliability: 0.92,
  },
  {
    id: "bumper-bugs",
    name: "Bumper Bugs",
    blurb: "Tiny cars, huge grudges. A gentle way to settle family disputes.",
    category: "ride",
    w: 3,
    h: 3,
    cost: 960,
    kind: "bumper",
    color: "#3d8b6e",
    roof: "#c9923a",
    height: 18,
    startUnlocked: true,
    excitement: 3.8,
    intensity: 2.6,
    nausea: 1.6,
    capacity: 8,
    duration: 10,
    runningCost: 16,
    reliability: 0.88,
  },
  {
    id: "teacup-tilt",
    name: "Teacup Tilt",
    blurb: "Spin the saucer. Spill the guest. Repeat.",
    category: "ride",
    w: 3,
    h: 3,
    cost: 1100,
    kind: "teacup",
    color: "#c24a3a",
    roof: "#e8dcc4",
    height: 16,
    startUnlocked: true,
    excitement: 4.1,
    intensity: 3.4,
    nausea: 3.8,
    capacity: 10,
    duration: 9,
    runningCost: 14,
    reliability: 0.9,
  },
  {
    id: "sky-ring",
    name: "Sky Ring",
    blurb: "A Ferris wheel. Fine-tune speed until it becomes a centrifuge. Legal says that's a feature.",
    category: "ride",
    w: 3,
    h: 3,
    cost: 1680,
    kind: "ferris",
    color: "#c24a3a",
    roof: "#f3ead7",
    height: 86,
    researchCost: 900,
    researchDays: 4,
    excitement: 5.2,
    intensity: 2.2,
    nausea: 1.2,
    capacity: 16,
    duration: 14,
    runningCost: 22,
    reliability: 0.86,
  },
  {
    id: "galleon",
    name: "The Galleon",
    blurb: "A pirate ship that can, against all advice, complete a 360.",
    category: "ride",
    w: 4,
    h: 2,
    cost: 1540,
    kind: "ship",
    color: "#6b4a32",
    roof: "#c24a3a",
    height: 42,
    researchCost: 850,
    researchDays: 4,
    excitement: 5.6,
    intensity: 4.8,
    nausea: 3.1,
    capacity: 14,
    duration: 11,
    runningCost: 20,
    reliability: 0.84,
  },
  {
    id: "the-plunge",
    name: "The Plunge",
    blurb: "A drop tower. Guests pay to fall. Physics sometimes collects a second fee.",
    category: "ride",
    w: 2,
    h: 2,
    cost: 2100,
    kind: "drop",
    color: "#2a3342",
    roof: "#c24a3a",
    height: 96,
    researchCost: 1200,
    researchDays: 5,
    excitement: 6.8,
    intensity: 7.4,
    nausea: 4.2,
    capacity: 8,
    duration: 12,
    runningCost: 28,
    reliability: 0.78,
  },
  {
    id: "mist-manor",
    name: "Mist Manor",
    blurb: "A haunted house. The ghosts are unionized. The screams are not.",
    category: "ride",
    w: 3,
    h: 3,
    cost: 1880,
    kind: "haunt",
    color: "#2a3342",
    roof: "#5c7f62",
    height: 48,
    researchCost: 1000,
    researchDays: 4,
    excitement: 5.8,
    intensity: 3.6,
    nausea: 2.4,
    capacity: 10,
    duration: 16,
    runningCost: 18,
    reliability: 0.9,
  },
  {
    id: "splash-run",
    name: "Splash Run",
    blurb: "Logs, water, one inevitable photograph. Keep towels in research.",
    category: "ride",
    w: 4,
    h: 3,
    cost: 2460,
    kind: "flume",
    color: "#3d6b8b",
    roof: "#c9923a",
    height: 28,
    researchCost: 1400,
    researchDays: 6,
    excitement: 6.2,
    intensity: 4.4,
    nausea: 2.8,
    capacity: 8,
    duration: 18,
    runningCost: 30,
    reliability: 0.82,
  },
  {
    id: "sky-chairs",
    name: "Sky Chairs",
    blurb: "Swings that pretend to be gentle until you raise the throttle.",
    category: "ride",
    w: 3,
    h: 3,
    cost: 1420,
    kind: "swing",
    color: "#c9923a",
    roof: "#c24a3a",
    height: 52,
    researchCost: 800,
    researchDays: 3,
    excitement: 4.9,
    intensity: 4.1,
    nausea: 2.9,
    capacity: 16,
    duration: 10,
    runningCost: 18,
    reliability: 0.87,
  },
  {
    id: "junior-twist",
    name: "Junior Twist",
    blurb: "A compact coaster. Training wheels for tomorrow's lawsuit.",
    category: "ride",
    w: 4,
    h: 4,
    cost: 2880,
    kind: "junior",
    color: "#3d8b6e",
    roof: "#c24a3a",
    height: 36,
    researchCost: 1600,
    researchDays: 6,
    excitement: 6.4,
    intensity: 5.2,
    nausea: 3.4,
    capacity: 12,
    duration: 16,
    runningCost: 34,
    reliability: 0.8,
  },
  {
    id: "custom-coaster",
    name: "Track Works",
    blurb: "Design your own coaster. If it returns to the station, we call it a success.",
    category: "ride",
    w: 3,
    h: 2,
    cost: 3200,
    kind: "coaster",
    color: "#c24a3a",
    roof: "#2a3342",
    height: 22,
    researchCost: 2200,
    researchDays: 4,
    excitement: 2.0,
    intensity: 2.0,
    nausea: 1.0,
    capacity: 10,
    duration: 20,
    runningCost: 40,
    reliability: 0.75,
  },
  {
    id: "dog-cart",
    name: "Mustard Cart",
    blurb: "Hot dogs of uncertain lineage. Guests do not ask. Guests do not tell.",
    category: "shop",
    w: 1,
    h: 1,
    cost: 260,
    kind: "stall",
    color: "#c24a3a",
    roof: "#f3ead7",
    height: 22,
    startUnlocked: true,
    product: "food",
    priceDefault: 3.5,
    serveTime: 2.2,
  },
  {
    id: "soda-fizz",
    name: "Fizz Tap",
    blurb: "Carbonated mystery. Cures thirst, causes opinions.",
    category: "shop",
    w: 1,
    h: 1,
    cost: 240,
    kind: "stall",
    color: "#3d6b8b",
    roof: "#f3ead7",
    height: 22,
    startUnlocked: true,
    product: "drink",
    priceDefault: 2.5,
    serveTime: 1.8,
  },
  {
    id: "candy-floss",
    name: "Cloud Sugar",
    blurb: "Cotton candy. 90% air, 10% regret, 100% queue.",
    category: "shop",
    w: 1,
    h: 1,
    cost: 220,
    kind: "stall",
    color: "#c24a3a",
    roof: "#e8dcc4",
    height: 22,
    startUnlocked: true,
    product: "sugar",
    priceDefault: 2,
    serveTime: 1.6,
  },
  {
    id: "scoop-shop",
    name: "Scoop Shop",
    blurb: "Ice cream. A civilizing force until it hits the path.",
    category: "shop",
    w: 2,
    h: 1,
    cost: 380,
    kind: "stall",
    color: "#e8dcc4",
    roof: "#3d8b6e",
    height: 24,
    researchCost: 400,
    researchDays: 2,
    product: "food",
    priceDefault: 3,
    serveTime: 2.4,
  },
  {
    id: "pizza-slice",
    name: "Park Slice",
    blurb: "Triangles of morale. Grease optional, lawsuits optional.",
    category: "shop",
    w: 2,
    h: 1,
    cost: 420,
    kind: "stall",
    color: "#c9923a",
    roof: "#c24a3a",
    height: 24,
    researchCost: 480,
    researchDays: 2,
    product: "food",
    priceDefault: 4.5,
    serveTime: 2.8,
  },
  {
    id: "balloon-box",
    name: "Balloon Box",
    blurb: "Helium and false hope. Children will not leave without one.",
    category: "shop",
    w: 1,
    h: 1,
    cost: 180,
    kind: "stall",
    color: "#c24a3a",
    roof: "#3d8b6e",
    height: 26,
    startUnlocked: true,
    product: "balloon",
    priceDefault: 2,
    serveTime: 1.4,
  },
  {
    id: "souvenir-hut",
    name: "Relic Hut",
    blurb: "Branded trinkets. The real product is the memory of spending.",
    category: "shop",
    w: 2,
    h: 1,
    cost: 360,
    kind: "stall",
    color: "#6b4a32",
    roof: "#c24a3a",
    height: 24,
    researchCost: 360,
    researchDays: 2,
    product: "souvenir",
    priceDefault: 8,
    serveTime: 2,
  },
  {
    id: "restroom",
    name: "Relief Block",
    blurb: "Toilets. Delete these and watch civilization recede in real time.",
    category: "shop",
    w: 2,
    h: 1,
    cost: 420,
    kind: "stall",
    color: "#c4b49a",
    roof: "#2a3342",
    height: 20,
    startUnlocked: true,
    product: "toilet",
    priceDefault: 0.5,
    serveTime: 3.2,
  },
  {
    id: "first-aid",
    name: "Patch Tent",
    blurb: "Bandages, ice packs, and a form for the helicopter invoice.",
    category: "shop",
    w: 2,
    h: 2,
    cost: 520,
    kind: "stall",
    color: "#c24a3a",
    roof: "#f3ead7",
    height: 22,
    researchCost: 500,
    researchDays: 3,
    product: "aid",
    priceDefault: 0,
    serveTime: 4,
  },
  {
    id: "oak",
    name: "Park Oak",
    blurb: "A tree. Guests point at it and feel cultured.",
    category: "scenery",
    w: 1,
    h: 1,
    cost: 25,
    kind: "tree",
    color: "#3f5c45",
    roof: "#5c7f62",
    height: 40,
    startUnlocked: true,
  },
  {
    id: "pine",
    name: "Sentinel Pine",
    blurb: "Tall, pointed, unbothered by screams.",
    category: "scenery",
    w: 1,
    h: 1,
    cost: 28,
    kind: "pine",
    color: "#2f4a36",
    roof: "#3f5c45",
    height: 52,
    startUnlocked: true,
  },
  {
    id: "flower",
    name: "Flower Bed",
    blurb: "Color without liability. A rare combination.",
    category: "scenery",
    w: 1,
    h: 1,
    cost: 18,
    kind: "flower",
    color: "#c24a3a",
    roof: "#c9923a",
    height: 8,
    startUnlocked: true,
  },
  {
    id: "lamp",
    name: "Lantern Post",
    blurb: "Light for the queues. Hope is extra.",
    category: "scenery",
    w: 1,
    h: 1,
    cost: 40,
    kind: "lamp",
    color: "#2a3342",
    roof: "#c9923a",
    height: 28,
    startUnlocked: true,
  },
  {
    id: "bench",
    name: "Waiting Bench",
    blurb: "A place to sit while considering the exit.",
    category: "scenery",
    w: 1,
    h: 1,
    cost: 32,
    kind: "bench",
    color: "#6b4a32",
    roof: "#c4b49a",
    height: 8,
    startUnlocked: true,
  },
  {
    id: "fountain",
    name: "Charter Fountain",
    blurb: "Water going up so guests forget the prices going up.",
    category: "scenery",
    w: 2,
    h: 2,
    cost: 380,
    kind: "fountain",
    color: "#3d6b8b",
    roof: "#e8dcc4",
    height: 26,
    researchCost: 280,
    researchDays: 2,
  },
  {
    id: "statue",
    name: "Founder Bust",
    blurb: "A bronze someone. The plaque is intentionally vague.",
    category: "scenery",
    w: 1,
    h: 1,
    cost: 220,
    kind: "statue",
    color: "#6b6a62",
    roof: "#c9923a",
    height: 24,
    researchCost: 200,
    researchDays: 2,
  },
  {
    id: "hedge",
    name: "Box Hedge",
    blurb: "Green walls. Containment, but make it horticulture.",
    category: "scenery",
    w: 1,
    h: 1,
    cost: 16,
    kind: "hedge",
    color: "#3f5c45",
    roof: "#5c7f62",
    height: 12,
    startUnlocked: true,
  },
  {
    id: "bin",
    name: "Litter Bin",
    blurb: "Optimistic architecture. Guests will miss it on purpose.",
    category: "scenery",
    w: 1,
    h: 1,
    cost: 20,
    kind: "bin",
    color: "#2a3342",
    roof: "#5c7f62",
    height: 10,
    startUnlocked: true,
  },
  {
    id: "janitor",
    name: "Groundskeeper",
    blurb: "Hunts litter and long grass. Loses to ice cream. Tries again.",
    category: "staff",
    w: 1,
    h: 1,
    cost: 80,
    kind: "staff",
    color: "#5c7f62",
    roof: "#c4b49a",
    height: 16,
    startUnlocked: true,
    wage: 55,
  },
  {
    id: "mechanic",
    name: "Ridewright",
    blurb: "Fixes what the physics engine invented this morning.",
    category: "staff",
    w: 1,
    h: 1,
    cost: 120,
    kind: "staff",
    color: "#c9923a",
    roof: "#2a3342",
    height: 16,
    startUnlocked: true,
    wage: 80,
  },
  {
    id: "mascot",
    name: "Captain Wonder",
    blurb: "A costume with eyes. Happiness goes up. Comfort does not.",
    category: "staff",
    w: 1,
    h: 1,
    cost: 90,
    kind: "staff",
    color: "#c24a3a",
    roof: "#f3ead7",
    height: 18,
    researchCost: 300,
    researchDays: 2,
    wage: 70,
  },
  {
    id: "entertainer",
    name: "Jester",
    blurb: "Stops in a crowd and performs. Happiness, briefly, becomes a spectator sport.",
    category: "staff",
    w: 1,
    h: 1,
    cost: 95,
    kind: "staff",
    color: "#e8c84a",
    roof: "#c24a3a",
    height: 18,
    startUnlocked: true,
    wage: 62,
  },
  {
    id: "medic",
    name: "Park Medic",
    blurb: "For when the helicopter is busy.",
    category: "staff",
    w: 1,
    h: 1,
    cost: 140,
    kind: "staff",
    color: "#c24a3a",
    roof: "#f3ead7",
    height: 16,
    researchCost: 420,
    researchDays: 3,
    wage: 90,
  },
  {
    id: "gardener",
    name: "Flower Hand",
    blurb: "Waters beds. Mows when the grass starts writing its own novel.",
    category: "staff",
    w: 1,
    h: 1,
    cost: 70,
    kind: "staff",
    color: "#3d8b6e",
    roof: "#c9923a",
    height: 16,
    startUnlocked: true,
    wage: 48,
  },
  {
    id: "security",
    name: "Park Watch",
    blurb: "For guests who treat benches as sport. Crowds notice the uniform.",
    category: "staff",
    w: 1,
    h: 1,
    cost: 110,
    kind: "staff",
    color: "#2a3342",
    roof: "#c24a3a",
    height: 16,
    startUnlocked: true,
    wage: 72,
  },
  {
    id: "park-map",
    name: "Map Kiosk",
    blurb: "A map. Guests without one will invent geography.",
    category: "shop",
    w: 1,
    h: 1,
    cost: 280,
    kind: "stall",
    color: "#c9923a",
    roof: "#2a3342",
    height: 22,
    startUnlocked: true,
    product: "info",
    priceDefault: 1.5,
    serveTime: 1.2,
  },
  {
    id: "flash-hut",
    name: "Flash Hut",
    blurb: "On-ride photographs. Proof you survived the throttle.",
    category: "shop",
    w: 2,
    h: 1,
    cost: 540,
    kind: "stall",
    color: "#2a3342",
    roof: "#c24a3a",
    height: 24,
    researchCost: 420,
    researchDays: 2,
    product: "photo",
    priceDefault: 6,
    serveTime: 2.2,
  },
  {
    id: "brolly-cart",
    name: "Brolly Cart",
    blurb: "Umbrellas. Rain is not a refund. The Board is very clear on this.",
    category: "shop",
    w: 1,
    h: 1,
    cost: 220,
    kind: "stall",
    color: "#2a3342",
    roof: "#3d6b8b",
    height: 20,
    startUnlocked: true,
    product: "umbrella",
    priceDefault: 4,
    serveTime: 1.1,
  },
  {
    id: "bandstand",
    name: "Bandstand",
    blurb: "A brass trio that never takes a break. Nearby queues forgive you.",
    category: "scenery",
    w: 2,
    h: 2,
    cost: 420,
    kind: "bandstand",
    color: "#c9923a",
    roof: "#c24a3a",
    height: 28,
    startUnlocked: true,
  },
];

export const DEF_MAP = Object.fromEntries(DEFS.map((d) => [d.id, d])) as Record<string, Def>;

/** Starter blueprints. Copied per park — research must never mutate this list. */
const START_UNLOCKED_IDS: readonly string[] = DEFS.filter((d) => d.startUnlocked).map((d) => d.id);

export const SCENARIOS: Scenario[] = [
  {
    id: "hollow",
    name: "Hollow Creek",
    place: "Assignment One",
    image: "/art/hollow.jpg",
    cash: 12500,
    biome: "creek",
    blurb: "A mothballed park beside a sulking creek. HQ wants it loud again.",
    briefing:
      "Hollow Creek closed in 1994 after an incident the archive files simply label 'weather'. You are to reopen it, fill it, and keep the rating respectable. The board is flexible about methods. They are less flexible about quarterly notes.",
    objectives: [
      { id: "path", text: "Lay a path from the gate into the park" },
      { id: "toilet", text: "Open a Relief Block" },
      { id: "food", text: "Open a food stall" },
      { id: "ride", text: "Open a working ride" },
      { id: "guests", text: "Host 40 guests at once" },
      { id: "rating", text: "Reach park rating 600" },
    ],
  },
  {
    id: "fernwood",
    name: "Fernwood Frontiers",
    place: "Assignment Two",
    image: "/art/fernwood.jpg",
    cash: 22000,
    biome: "forest",
    blurb: "A lush clearing. Build wonder without flattening the pines. Mostly.",
    briefing:
      "Fernwood is a showpiece for visiting directors. They want a custom coaster, a rating that photographs well, and fewer airborne guests than Hollow Creek. Try to keep the trees. Try harder to keep the train on the rails.",
    objectives: [
      { id: "trees", text: "Keep at least 12 trees standing" },
      { id: "coaster", text: "Build and test a Track Works coaster" },
      { id: "guests", text: "Host 55 guests at once" },
      { id: "profit", text: "Hold $8,000 cash" },
      { id: "rating", text: "Reach park rating 700" },
    ],
  },
];

export function defById(id: string): Def {
  const d = DEF_MAP[id];
  if (!d) throw new Error(`Unknown def ${id}`);
  return d;
}

export function startingUnlocked(): string[] {
  return START_UNLOCKED_IDS.slice();
}

export function isStarterBlueprint(id: string): boolean {
  return START_UNLOCKED_IDS.includes(id);
}
